apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml -f docker-compose-prod.yml -o .k8s
    kompose.image-pull-secret: ungpregcredtoken
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: graphdb
  name: graphdb
spec:
  ports:
  - name: "7200"
    port: 7200
    targetPort: 7200
  selector:
    io.kompose.service: graphdb
status:
  loadBalancer: {}
