version: '3.1'
services: 
  proxy: 
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/proxy-prod:v0.4'
    build:
      context: ./proxy
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
      #- NGINX_HOST=${HOST}
      #- NGINX_PORT=80
    command: /bin/sh -c "cp /etc/nginx/conf.d/nginx.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
      kompose.service.type: LoadBalancer
      kompose.service.expose: "true"
  webapp:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/webapp-prod:v0.4'
    build:
      context: ./webapp
      dockerfile: prod.Dockerfile
      args:
      - NGINX_HOST=${HOST}
    restart: always
    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    expose:
      - "81"
    ports:
      - "81:81"
    labels:
      kompose.image-pull-secret: ungpregcredtoken
#volumes:
#  graph-data:
#networks:
#  sdgnet: