version: '3.1'
services: 
  proxy: 
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/proxy:prod-latest'
    build:
      context: ./proxy
      dockerfile: Dockerfile
    environment:
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/nginx.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  graph:
    environment: 
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
  concepts:
    environment: 
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
  text:
    environment: 
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
  webapp:
    environment: 
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
