version: '3.1'
services: 
  proxy: 
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/proxy:v0.4.3'
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
      - NGINX_HOST=${HOST}
      - NGINX_PORT=${PORT}
    command: /bin/sh -c "cp /etc/nginx/conf.d/nginx.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
      kompose.service.type: LoadBalancer
      kompose.service.expose: "true"
  graphdb:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/graphdb:v0.4.3'
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3030"
    ports:
      - "3030:3030"
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
  graph:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/graph:v0.4.3'
    build:
      context: ./graph
      dockerfile: Dockerfile
    restart: always
    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    expose:
      - "5002"
    ports:
      - "5002:5002"
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
  concepts:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/concepts:v0.4.3'
    build:
      context: ./concepts
      dockerfile: Dockerfile
    restart: always
    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    expose:
      - "5000"
    ports:
      - "5000:5000"
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
  text:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/text:v0.4.3'
    build:
      context: ./text
      dockerfile: Dockerfile
    restart: always
    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    expose:
      - "5001"
    ports:
      - "5001:5001"
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
  sdg:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/sdgapi:v0.4.3'
    build:
      context: ./sdgapi
      dockerfile: Dockerfile
    restart: always
    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    expose:
      - "4000"
    ports:
      - "4000:4000"
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
  swaggerapi:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/swaggerapi:v0.4.3'
    build:
      context: ./swaggerapi
      dockerfile: Dockerfile
    restart: always
    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    expose:
      - "5003"
    ports:
      - "5003:5003"
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
      
  webapp:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/webapp:v0.4.3'
    build:
      context: ./webapp
      dockerfile: Dockerfile
      args:
      - NGINX_HOST=${HOST}
    restart: always
    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=720080
    expose:
      - "81"
    ports:
      - "81:81"
    labels:
      kompose.image-pull-secret: ungpregcredtoken
#volumes:
#  graph-data:
#networks:
#  sdgnet:


