version: '3.1'
services: 
  proxy: 
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/proxy:latest'
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/nginx.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    #networks:
    #  sdgnet:
    #    ipv4_address: 172.28.238.10
        #aliases:
        #  - proxy.sdgontologies.svc.cluster.local
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
      kompose.service.type: LoadBalancer
      kompose.service.expose: "true"
  graphdb:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/graphdb:latest'
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
#    volumes: 
#       - graph-data:/opt/graphdb/home
    expose:
      - "7200"
    ports:
      - "7200:7200"
    #networks:
    #  sdgnet:
    #    ipv4_address: 172.28.238.20
        #aliases:
        #  - graphdb.sdgontologies.svc.cluster.local
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
  graph:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/graph:latest'
    build:
      context: ./graph
      dockerfile: Dockerfile
    restart: always
    links:
      - "graphdb:graphdb.sdgontologies.svc.cluster.local"

    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    expose:
      - "5002"
    ports:
      - "5002:5002"
    #networks:
    #  sdgnet:
    #    ipv4_address: 172.28.238.30
        #aliases:
        #  - graph.sdgontologies.svc.cluster.local
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
  concepts:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/concepts:latest'
    build:
      context: ./concepts
      dockerfile: Dockerfile
    restart: always
    links:
      - "graphdb:graphdb.sdgontologies.svc.cluster.local"
    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    expose:
      - "5000"
    ports:
      - "5000:5000"
    #networks:
    #  sdgnet:
    #    ipv4_address: 172.28.238.40
        #aliases:
        #  - concepts.sdgontologies.svc.cluster.local
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
  text:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/text:latest'
    build:
      context: ./text
      dockerfile: Dockerfile
    restart: always
    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    expose:
      - "5001"
    ports:
      - "5001:5001"
    #networks:
    #  sdgnet:
    #    ipv4_address: 172.28.238.50
        #aliases:
        #  - text.sdgontologies.svc.cluster.local
    labels:
      kompose.image-pull-secret: "ungpregcredtoken"
  webapp:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/webapp:latest'
    build:
      context: ./webapp
      dockerfile: Dockerfile
    restart: always
    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    expose:
      - "81"
    ports:
      - "81:81"
    #networks:
    #  sdgnet:
    #    ipv4_address: 172.28.238.60
        #aliases:
        #  - webapp.sdgontologies.svc.cluster.local
    labels:
      kompose.image-pull-secret: ungpregcredtoken
#volumes:
#  graph-data:
#networks:
#  sdgnet:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.238.0/24