version: '3.1'
services: 
  proxy: 
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/proxy:prod-latest'
    build:
      context: ./proxy
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    environment:
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
      - NGINX_HOST=linkedsdgs.apps.officialstatistics.org
      - NGINX_PORT=80
    command: /bin/sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/nginx-prod.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  webapp:
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/webapp-prod:latest'
    build:
      context: ./webapp
      dockerfile: prod.Dockerfile
      args:
        - NGINX_HOST=linkedsdgs.apps.officialstatistics.org
        - NGINX_PORT=80
    restart: always
    environment: 
      - GET_HOSTS_FROM=dns
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    expose:
      - "81"
    ports:
      - "81:81"
    #networks:
    #  sdgnet:
    #    ipv4_address: 172.28.238.60
        #aliases:
        #  - webapp.sdgontologies.svc.cluster.local
