version: '3.1'
services: 
  proxy: 
    image: 'containers.officialstatistics.org/cslovell/sdg-docker-ontologies/proxy:prod-latest'
    build:
      context: ./proxy
      dockerfile: Dockerfile.prod
    environment:
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
    command: /bin/sh -c "nginx -g 'daemon off;'"
  graph:
    environment: 
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
  concepts:
    environment: 
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
  text:
    environment: 
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
  webapp:
    environment: 
      - GRAPHDB_REPO=sdgs-data
      - GRAPHDB_PORT=7200
