apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: proxy
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - envsubst '$NGINX_HOST $NGINX_PORT' < /etc/nginx/conf.d/nginx.template >
          /etc/nginx/nginx.conf && nginx -g 'daemon off;'
        env:
        - name: GRAPHDB_PORT
        - name: GRAPHDB_REPO
        - name: GRAPHDB_URL
        - name: GRAPHDB_USE_HTTPS
        - name: NGINX_HOST
        - name: NGINX_PORT
        image: proxy
        name: proxy
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
