apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webapp
    spec:
      containers:
      - env:
        - name: GRAPHDB_PORT
        - name: GRAPHDB_REPO
        - name: GRAPHDB_URL
        - name: GRAPHDB_USE_HTTPS
        image: webapp
        name: webapp
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
