apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml -f docker-compose-prod.yml
    kompose.image-pull-secret: ungpregcredtoken
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: graphdb
  name: graphdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: graphdb
    spec:
      containers:
      - image: containers.officialstatistics.org/cslovell/sdg-docker-ontologies/graphdb:latest
        name: graphdb
        resources: {}
        volumeMounts:
        - mountPath: /opt/graphdb/home
          name: graph-data
      restartPolicy: Always
      volumes:
      - name: graph-data
        persistentVolumeClaim:
          claimName: graph-data
status: {}
