# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources 
namespace: sdgontologies-staging-$(TAG)

configMapGenerator:
  - name: common-config
    env: common.env
    namespace: sdgontologies-staging-$(TAG)
#secretGenerator:
#  - name: common-secret
#    env: common-secret.env    
#    namespace: ontologies-test

images:
  - name: containers.officialstatistics.org/cslovell/sdg-docker-ontologies/proxy
    newTag: staging-$(TAG)
  - name: containers.officialstatistics.org/cslovell/sdg-docker-ontologies/graphdb
    newTag: staging-$(TAG)
  - name: containers.officialstatistics.org/cslovell/sdg-docker-ontologies/graph
    newTag: staging-$(TAG)
  - name: containers.officialstatistics.org/cslovell/sdg-docker-ontologies/concepts
    newTag: staging-$(TAG)
  - name: containers.officialstatistics.org/cslovell/sdg-docker-ontologies/text
    newTag: staging-$(TAG)
  - name: containers.officialstatistics.org/cslovell/sdg-docker-ontologies/sdgapi
    newTag: staging-$(TAG)
  - name: containers.officialstatistics.org/cslovell/sdg-docker-ontologies/swaggerapi
    newTag: staging-$(TAG)
  - name: containers.officialstatistics.org/cslovell/sdg-docker-ontologies/webapp
    newTag: staging-$(TAG)

resources:
- graphdb.deployment.yaml
- graph.deployment.yaml
- text.deployment.yaml
- concepts.deployment.yaml
- webapp.deployment.yaml
- swaggerapi.deployment.yaml
- sdg.deployment.yaml
- proxy.deployment.yaml
- proxy-ingress.yaml
